checks:
    php:
        code_rating: true
        duplication: true

build:
  environment:
    php: "7.0.8"

  tests:
      before:
          - "phpunit"

before_commands:
    - "composer install --no-interaction --prefer-source"